task_manager/labels/urls.py
from django.urls import path
from .views import LabelListView, LabelCreateView, LabelUpdateView, LabelDeleteView

app_name = 'labels'

urlpatterns = [
    path('', LabelListView.as_view(), name='label_list'),
    path('create/', LabelCreateView.as_view(), name='label_create'),
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='label_update'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='label_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from task_manager.views import IndexView, LoginView, LogoutView, SettingsView

urlpatterns = i18n_patterns(
    # Admin
    path("admin/", admin.site.urls),

    # Auth routes
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Main routes
    path('', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),

    # App-specific routes
    path('users/', include('task_manager.users.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('projects/', include('task_manager.projects.urls')),
    path('dashboard/', include('task_manager.dashboard.urls')),
)

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms
from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']


class FilterForm(forms.Form):
    name = forms.CharField(max_length=100, required=False,
                           widget=forms.TextInput(attrs={'placeholder': 'Имя метки'}))
    not_used = forms.BooleanField(required=False, label="Не используется")

task_manager/labels/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from task_manager.mixins import CustomLoginRequiredMixin
from .models import Label
from .forms import LabelForm, FilterForm
from django.utils.translation import gettext as _


class LabelListView(CustomLoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/labels.html'
    context_object_name = 'labels'

    def get_queryset(self):
        labels = super().get_queryset()
        form = FilterForm(self.request.GET)
        if form.is_valid():
            name_search = form.cleaned_data.get('name')
            not_used = form.cleaned_data.get('not_used')
            if name_search:
                labels = labels.filter(name__icontains=name_search)
            if not_used:
                labels = labels.filter(tasks=None)
        return labels


class LabelCreateView(CustomLoginRequiredMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/label_create.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        messages.success(self.request, _('Метка успешно создана'))
        return super().form_valid(form)


class LabelUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/label_update.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        messages.success(self.request, _('Метка успешно изменена'))
        return super().form_valid(form)


class LabelDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Label
    template_name = 'labels/label_delete.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        self.object = self.get_object()
        if self.object.tasks.exists():
            messages.error(self.request, _('Невозможно удалить метку, связанную с задачами.'))
            return redirect('labels:label_list')
        messages.success(self.request, _('Метка успешно удалена'))
        return super().form_valid(form)

templates/labels/label_create.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}

{% block content %}
<div class="container">
  <h1 class="my-4">{% trans "Создать метку" %}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group mt-3 col-md-6">
        <label for="id_name">{% trans "Имя" %}</label>
        <input type="text" class="form-control" id="id_name" name="name">
    </div>
    <div class="form-group mt-4">
        <button type="submit" class="btn btn-outline-dark">{% trans "Создать" %}</button>
    </div>
  </form>
</div>
{% endblock %}

templates/labels/label_delete.html
{% extends 'task_manager/layout.html' %}

{% load i18n %}

{% block content %}
<div class="container">
  <h1 class="my-4">
    {% trans "Удалить метку" %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">{% trans "Да, удалить" %}</button>
    <a href="{% url 'labels:label_list' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
  </form>
</div>
{% endblock %}

templates/labels/label_update.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}

{% block content %}
<div class="container">
  <h1 class="my-4">{% trans "Изменение метки" %}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group mt-3 col-md-6">
        <label for="id_name">{% trans "Имя" %}</label>
        <input type="text" class="form-control" id="id_name" name="name" value="{{ label.name }}">
    </div>
    <div class="form-group mt-4">
        <button type="submit" class="btn btn-outline-dark">{% trans "Изменить" %}</button>
    </div>
  </form>
</div>
{% endblock %}

templates/labels/labels.html
{% load i18n %}
{% block content %}
<div class="container">
  <div class="d-flex flex-wrap mt-5">
    {% for label in labels %}
    <span class="badge bg-secondary rounded-pill mr-2 mb-2 d-flex align-items-center">
      {{ label.name }}
      <a href="{% url 'labels:label_update' label.id %}" class="btn btn-link btn-sm ml-2 p-0">
        <i class="bi bi-pencil text-white"></i>
      </a>
      <a href="{% url 'labels:label_delete' label.id %}" class="btn btn-link btn-sm ml-2 p-0">
        <i class="bi bi-trash text-white"></i>
      </a>
    </span>
    {% empty %}
    <p>{% trans "Нет меток." %}</p>
    {% endfor %}
    <a href="{% url 'labels:label_create' %}" class="text-secondary" style="font-size: 24px; transition: color 0.3s;">
        <i class="bi bi-plus-circle"></i>
    </a>
  </div>
</div>
<div class="mb-5"></div>
{% endblock %}