task_manager/projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='projects_list'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from task_manager.views import IndexView, LoginView, LogoutView, SettingsView

urlpatterns = i18n_patterns(
    # Admin
    path("admin/", admin.site.urls),

    # Auth routes
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Main routes
    path('', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),

    # App-specific routes
    path('users/', include('task_manager.users.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('projects/', include('task_manager.projects.urls')),
    path('dashboard/', include('task_manager.dashboard.urls')),
)

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

task_manager/projects/models.py
from django.db import models
from task_manager.users.models import User


class Project(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

task_manager/projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name']

task_manager/projects/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from task_manager.mixins import CustomLoginRequiredMixin
from .models import Project
from .forms import ProjectForm
from django.utils.translation import gettext as _


class ProjectListView(CustomLoginRequiredMixin, ListView):
    model = Project
    template_name = 'projects/projects.html'
    context_object_name = 'projects'


class ProjectCreateView(CustomLoginRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_create.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        messages.success(self.request, _('Проект успешно создан'))
        return super().form_valid(form)


class ProjectUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_update.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        messages.success(self.request, _('Проект успешно обновлен'))
        return super().form_valid(form)


class ProjectDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'projects/project_delete.html'
    success_url = reverse_lazy('settings')

    def form_valid(self, form):
        self.object = self.get_object()
        if self.object.task_set.exists():
            messages.error(self.request, _('Невозможно удалить проект, связанный с задачами.'))
            return redirect('projects:projects_list')
        self.object.__class__.objects.filter(id=self.object.id).delete()
        messages.success(self.request, _('Проект успешно удален'))
        return super().form_valid(form)

templates/projects/project_create.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}

{% block content %}
<div class="container">
  <h1 class="my-4">{% trans "Создать проект" %}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group mt-3 col-md-6">
        <label for="id_name">{% trans "Имя" %}</label>
        <input type="text" class="form-control" id="id_name" name="name">
    </div>
    <div class="form-group mt-3 col-md-6">
        <label for="id_created_by">{% trans "Создатель" %}</label>
        <input type="text" class="form-control" id="id_created_by" name="created_by" readonly value="{{ request.user.username }}">
    </div>
    <div class="form-group mt-4">
        <button type="submit" class="btn btn-outline-dark">{% trans "Создать" %}</button>
    </div>
  </form>
</div>
{% endblock %}

templates/projects/project_delete.html
{% extends 'task_manager/layout.html' %}

{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Удаление проекта" %}</h2>
    <form method="post">
        {% csrf_token %}
        <p>{% trans "Вы уверены, что хотите удалить проект" %} {{ project.name }}?</p>
        <button type="submit" class="btn btn-danger">{% trans "Да, удалить" %}</button>
        <a href="{% url 'projects:projects_list' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
    </form>
</div>
{% endblock %}

templates/projects/project_update.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}

{% block content %}
<div class="container">
  <h1 class="my-4">{% trans "Изменение проекта" %}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group mt-3 col-md-6">
        <label for="id_name">{% trans "Имя" %}</label>
        <input type="text" class="form-control" id="id_name" name="name" value="{{ project.name }}">
    </div>
    <div class="form-group mt-3 col-md-6">
        <label for="id_created_by">{% trans "Создатель" %}</label>
        <input type="text" class="form-control" id="id_created_by" name="created_by" value="{{ project.created_by }}" readonly>
    </div>
    <div class="form-group mt-4">
        <button type="submit" class="btn btn-outline-dark">{% trans "Изменить" %}</button>
    </div>
  </form>
</div>
{% endblock %}

templates/projects/projects.html
{% load i18n %}
{% block content %}
<div class="container">
  <div class="form-group m-4 ml-auto">
    <a href="{% url 'projects:project_create' %}" class="btn btn-outline-dark">{% trans "Создать проект" %}</a>
  </div>
  <table class="table table-hover">
    <thead class="bg-light">
        <tr>
            <th width="10%">{% trans "ID" %}</th>
            <th width="30%">{% trans "Имя" %}</th>
            <th width="30%">{% trans "Дата создания" %}</th>
            <th width="20%">{% trans "Создатель" %}</th>
            <th width="10%"></th>
        </tr>
    </thead>
    <tbody>
      {% for project in projects %}
        <tr>
          <td>{{ project.id }}</td>
          <td>{{ project.name }}</td>
          <td>{{ project.created_at|date:"d.m.Y H:i" }}</td>
          <td>{{ project.created_by }}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Действия">
              <a href="{% url 'projects:project_update' project.id %}" class="btn btn-link">
                <i class="bi bi-pencil text-secondary"></i>
              </a>
              <a href="{% url 'projects:project_delete' project.id %}" class="btn btn-link">
                <i class="bi bi-trash text-secondary"></i>
              </a>
            </div>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">{% trans "Нет проектов." %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="mb-5"></div>
{% endblock %}