task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from task_manager.views import IndexView, LoginView, LogoutView, SettingsView

urlpatterns = i18n_patterns(
    # Admin
    path("admin/", admin.site.urls),

    # Auth routes
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Main routes
    path('', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),

    # App-specific routes
    path('users/', include('task_manager.users.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('projects/', include('task_manager.projects.urls')),
    path('dashboard/', include('task_manager.dashboard.urls')),
)

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

task_manager/users/urls.py
from django.urls import path
from .views import UserListView, RegisterView, UpdateUserView, DeleteUserView

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='users'),
    path('create/', RegisterView.as_view(), name='register'),
    path('<int:pk>/update/', UpdateUserView.as_view(), name='update_user'),
    path('<int:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "password1", "password2"]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

task_manager/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import FormView, DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy
from task_manager.mixins import CustomLoginRequiredMixin
from .models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .forms import RegisterForm, UserUpdateForm
from django.utils.translation import gettext as _


class UserListView(View):
    def get(self, request):
        users = User.objects.all()
        return render(request, 'users/users.html', {'users': users})


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, _("Пользователь успешно зарегистрирован"))
        return super().form_valid(form)

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{field}: {error}")
        return super().form_invalid(form)


class UpdateUserView(CustomLoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update_user.html'
    success_url = reverse_lazy('settings')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user == self.object:
            return super().dispatch(request, *args, **kwargs)
        else:
            messages.error(self.request, _("У вас нет прав для изменения другого пользователя."))
            return redirect('settings')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, _("Пользователь успешно изменен"))
        update_session_auth_hash(self.request, form.instance)
        return super().form_valid(form)

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{field}: {error}")
        return self.render_to_response(self.get_context_data(form=form))


class DeleteUserView(CustomLoginRequiredMixin, DeleteView):
    model = User
    template_name = 'users/delete_user.html'
    success_url = reverse_lazy('settings')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user == self.object:
            return super().dispatch(request, *args, **kwargs)
        else:
            messages.error(self.request, _("У вас нет прав для изменения другого пользователя."))
            return redirect('settings')

    def form_valid(self, form):
        messages.success(self.request, _("Пользователь успешно удален"))
        return super().form_valid(form)

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{field}: {error}")
        return super().form_invalid(form)


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('/')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(self.request, user)
                messages.info(self.request, _("Вы залогинены"))
            else:
                messages.error(self.request, _("Этот аккаунт отключен."))
        else:
            messages.error(self.request, _("Неверное имя пользователя или пароль."))
        return super().form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, _("Вы разлогинены"))
        return redirect('login')

templates/users/delete_user.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Удаление пользователя" %}</h2>
    <form method="post">
        {% csrf_token %}
        <p>{% trans "Вы уверены, что хотите удалить пользователя" %}{{ user.username }}?</p>
        <button type="submit" class="btn btn-danger">{% trans "Да, удалить" %}</button>
        <a href="{% url 'users:users' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
    </form>
</div>
{% endblock %}

templates/users/register.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Регистрация нового пользователя" %}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group mt-3 col-md-6">
            <label for="id_username">{% trans "Имя пользователя" %}</label>
            <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value|default:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_first_name">{% trans "Имя" %}</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name"
                   value="{{ form.first_name.value|default:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_last_name">{% trans "Фамилия" %}</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.last_name.value|default:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_password1">{% trans "Пароль" %}</label>
            <input type="password" class="form-control" id="id_password1" name="password1">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_password2">{% trans "Подтверждение пароля" %}</label>
            <input type="password" class="form-control" id="id_password2" name="password2">
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-outline-dark">{% trans "Зарегистрировать" %}</button>
        </div>
    </form>
</div>


{% endblock %}

templates/users/update_user.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Изменение пользователя" %}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group mt-3 col-md-6">
            <label for="id_first_name">{% trans "Имя" %}</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name|default_if_none:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_last_name">{% trans "Фамилия" %}</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.last_name|default_if_none:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_username">{% trans "Имя пользователя" %}</label>
            <input type="text" class="form-control" id="id_username" name="username" value="{{ user.username|default_if_none:'' }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_password1">{% trans "Пароль" %}</label>
            <input type="password" class="form-control" id="id_password1" name="password1">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_password2">{% trans "Подтверждение пароля" %}</label>
            <input type="password" class="form-control" id="id_password2" name="password2">
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-outline-dark">{% trans "Изменить" %}</button>
        </div>
    </form>
</div>
{% endblock %}

templates/users/users.html
{% load i18n %}
{% block content %}
<div class="container">
    <table class="table table-hover mt-5">
        <thead class="bg-light">
            <tr>
                <th>ID</th>
                <th>{% trans "Имя пользователя" %}</th>
                <th>{% trans "Полное имя" %}</th>
                <th>{% trans "Дата создания" %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.date_joined|date:"d.m.Y H:i" }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Действия">
                      <a href="{% url 'users:update_user' user.id %}" class="btn btn-link">
                        <i class="bi bi-pencil text-secondary" aria-label="Изменить"></i>
                      </a>
                      <a href="{% url 'users:delete_user' user.id %}" class="btn btn-link">
                        <i class="bi bi-trash text-secondary" aria-label="Удалить"></i>
                      </a>
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">{% trans "Нет пользователей." %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="mb-5"></div>
</div>
{% endblock %}