task_manager/tasks/urls.py
from django.urls import path
from .views import TaskDetailView, TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView

app_name = 'tasks'

urlpatterns = [
    path('', TaskListView.as_view(), name='tasks_list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from task_manager.views import IndexView, LoginView, LogoutView, SettingsView

urlpatterns = i18n_patterns(
    # Admin
    path("admin/", admin.site.urls),

    # Auth routes
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Main routes
    path('', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),

    # App-specific routes
    path('users/', include('task_manager.users.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('projects/', include('task_manager.projects.urls')),
    path('dashboard/', include('task_manager.dashboard.urls')),
)

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

task_manager/tasks/models.py
from django.db import models
from django.conf import settings
from task_manager.labels.models import Label
from task_manager.projects.models import Project


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    status = models.ForeignKey('statuses.Status', on_delete=models.CASCADE)
    priority = models.ForeignKey('priorities.Priority', on_delete=models.CASCADE)
    labels = models.ManyToManyField(Label, related_name='tasks', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='author_tasks')
    executor = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 related_name='assigned_tasks',
                                 blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_closed = models.BooleanField(default=False)

task_manager/tasks/forms.py
from django import forms
from .models import Task
from task_manager.statuses.models import Status
from task_manager.users.models import User
from task_manager.labels.models import Label
from task_manager.priorities.models import Priority


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'priority', 'executor', 'labels', 'project']


class FilterForm(forms.Form):
    name = forms.CharField(max_length=100,
                           required=False,
                           widget=forms.TextInput(attrs={'placeholder': 'Имя задачи'}))
    status = forms.ModelChoiceField(queryset=Status.objects.all(),
                                    required=False,
                                    empty_label="---------")
    priority = forms.ModelChoiceField(queryset=Priority.objects.all(),
                                      required=False,
                                      empty_label="---------")
    executor = forms.ModelChoiceField(queryset=User.objects.all(),
                                      required=False,
                                      empty_label="---------")
    label = forms.ModelChoiceField(queryset=Label.objects.all(),
                                   required=False, empty_label="Метка")
    only_mine = forms.BooleanField(required=False,
                                   label="Только мои")

task_manager/tasks/views.py
from django.shortcuts import redirect
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from django_filters.views import FilterView
from task_manager.mixins import CustomLoginRequiredMixin
from .filters import TaskFilter
from .forms import TaskForm, FilterForm
from .models import Task
from task_manager.statuses.models import Status
from task_manager.users.models import User
from task_manager.labels.models import Label
from django.contrib import messages
from django.utils.translation import gettext as _
from django.views.generic import DetailView
from task_manager.priorities.models import Priority
from task_manager.projects.models import Project


class TaskDetailView(CustomLoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'


class TaskListView(CustomLoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter

    def get_filterset_kwargs(self, filterset_class):
        kwargs = super().get_filterset_kwargs(filterset_class)
        kwargs.update({'request': self.request})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FilterForm(self.request.GET)
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        context['users'] = User.objects.all()
        context['labels'] = Label.objects.all()
        context['projects'] = Project.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        filterset = self.filterset_class(self.request.GET, queryset=queryset)
        queryset = filterset.qs
        is_closed = self.request.GET.get('is_closed', None)
        if is_closed == 'on':
            queryset = queryset.filter(is_closed=False)
        return queryset


class TaskCreateView(CustomLoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_create.html'
    success_url = reverse_lazy('tasks:tasks_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, _('Задача успешно создана'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FilterForm(self.request.GET)
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        context['users'] = User.objects.all()
        context['labels'] = Label.objects.all()
        context['projects'] = Project.objects.all()
        return context


class TaskUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_update.html'
    success_url = reverse_lazy('tasks:tasks_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        context['labels'] = Label.objects.all()
        context['users'] = User.objects.all()
        context['projects'] = Project.objects.all()
        return context

    def form_valid(self, form):
        task = form.instance
        if task.status.order in [0, 1]:
            task.is_closed = True
            task.save()
        messages.success(self.request, _('Задача успешно изменена'))
        return super().form_valid(form)


class TaskDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks/task_delete.html'
    success_url = reverse_lazy('tasks:tasks_list')

    def form_valid(self, form):
        task = self.get_object()
        if task.author != self.request.user:
            messages.error(self.request, _('Вы не можете удалить эту задачу'))
            return redirect('tasks:tasks_list')
        messages.success(self.request, _('Задача успешно удалена'))
        return super().form_valid(form)

templates/tasks/task_create.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Создать задачу" %}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group mt-3 col-md-6">
            <label for="id_name">{% trans "Имя" %}</label>
            <input type="text" class="form-control" id="id_name" name="name">
        </div>
        <div class="form-group mt-3 col-md-6">
          <label for="id_description">{% trans "Описание" %}</label>
          <textarea class="form-control" id="id_description" name="description" rows="5"></textarea>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_project">{% trans "Проект" %}</label>
            <select class="form-select" id="id_project" name="project">
                <option value="" selected> </option>
                {% for project in projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label class="form-label" for="id_status">{% trans "Статус" %}</label>
            <select class="form-select" id="id_status" name="status">
                <option value="" selected> </option>
                {% for status in statuses %}
                    <option value="{{ status.id }}">{{ status.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label class="form-label" for="id_priority">{% trans "Приоритет" %}</label>
            <select class="form-select" id="id_priority" name="priority">
                <option value="" selected> </option>
                {% for priority in priorities %}
                    <option value="{{ priority.id }}">{{ priority.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_executor" class="form-label">{% trans "Исполнитель" %}</label>
            <select class="form-select" id="id_executor" name="executor">
                <option value="" selected> </option>
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.get_full_name|default:user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_labels">{% trans "Метки" %}</label>
            <select multiple class="form-select" id="id_labels" name="labels">
                {% for label in labels %}
                    <option value="{{ label.id }}">{{ label.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-outline-dark" name="submit">{% trans "Создать" %}</button>
        </div>
    </form>
</div>
{% endblock %}

templates/tasks/task_delete.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Удаление задачи" %}</h2>
    <form method="post">
        {% csrf_token %}
        <p>{% trans "Вы уверены, что хотите удалить задачу" %} "{{ task.name }}"?</p>
        <button type="submit" class="btn btn-danger">{% trans "Да, удалить" %}</button>
        <a href="{% url 'tasks:tasks_list' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
    </form>
</div>
{% endblock %}

templates/tasks/task_detail.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container mt-5">

  <h1 class="mb-5">
    {% trans "Просмотр задачи" %}
  </h1>

  <div class="card col-sm-8 col-md-6 col-lg-4 mx-auto">
    <div class="card-header d-flex bg-secondary text-white justify-content-between align-items-center">
      <h5 class="card-title mb-0">{{ task.name }}</h5>
      <div class="btn-group" role="group" aria-label="Действия">
        <a href="{% url 'tasks:task_update' task.id %}" class="btn btn-link" title="{% trans 'Редактировать' %}">
          <i class="bi bi-pencil text-white"></i>
        </a>
        <a href="{% url 'tasks:task_delete' task.id %}" class="btn btn-link" title="{% trans 'Удалить' %}">
          <i class="bi bi-trash text-white"></i>
        </a>
      </div>
    </div>
    <div class="card-body">
      <div class="text-muted bg-light p-3 rounded mb-3">
        <div class="d-flex justify-content-between">
          <div class="small">{% trans "Исполнитель" %}: {{ task.executor.get_full_name|default:task.executor.username }}</div>
          <div class="small">{% trans "Статус" %}: {{ task.status.name }}</div>
          <div class="small">{% trans "Приоритет" %}: {{ task.priority.name }}</div>
        </div>
        <div class="d-flex justify-content-between mt-2">
          <div class="small">{% trans "Автор" %}: {{ task.author.get_full_name|default:task.author.username }}</div>
          <div class="small">{% trans "Создана" %}: {{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>
      </div>
      <hr class="my-3">
      <p class="card-text">{{ task.description }}</p>
      <div class="card-footer text-muted pt-2 bg-transparent border-0">
        {% for label in task.labels.all %}
          <span class="badge bg-secondary rounded-pill me-2">{{ label.name }}</span>
        {% endfor %}
      </div>
    </div>
  </div>

</div>
{% endblock %}

templates/tasks/task_update.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <h2>{% trans "Изменение задачи" %}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group mt-3 col-md-6">
            <label for="id_name">{% trans "Имя" %}</label>
            <input type="text" class="form-control" id="id_name" name="name" value="{{ task.name }}">
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_description">{% trans "Описание" %}</label>
            <textarea class="form-control" id="id_description" name="description">{{ task.description }}</textarea>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_project">{% trans "Проект" %}</label>
            <select class="form-select" id="id_project" name="project">
                <option value="" selected> </option>
                {% for project in projects %}
                    <option value="{{ project.id }}" {% if project == task.project %}selected{% endif %}>{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_status">{% trans "Статус" %}</label>
            <select class="form-select" id="id_status" name="status">
                {% for status in statuses %}
                    <option value="{{ status.id }}" {% if status == task.status %}selected{% endif %}>{{ status.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_priority">{% trans "Приоритет" %}</label>
            <select class="form-select" id="id_priority" name="priority">
                {% for priority in priorities %}
                    <option value="{{ priority.id }}" {% if priority == task.priority %}selected{% endif %}>{{ priority.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_executor">{% trans "Исполнитель" %}</label>
            <select class="form-select" id="id_executor" name="executor">
                {% for user in users %}
                    <option value="{{ user.id }}" {% if user == task.executor %}selected{% endif %}>{{ user.get_full_name|default:user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-3 col-md-6">
            <label for="id_labels">{% trans "Метки" %}</label>
            <select multiple class="form-select" id="id_labels" name="labels">
                {% for label in labels %}
                    <option value="{{ label.id }}" {% if label in task.labels.all %}selected{% endif %}>{{ label.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-outline-dark">{% trans "Изменить" %}</button>
        </div>
    </form>
</div>
{% endblock %}

templates/tasks/tasks.html
{% extends 'task_manager/layout.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container">
  <h1 class="my-4">
    {% trans "Задачи" %}
  </h1>

    <!-- Форма фильтрации -->
    <form method="get" class="row mb-4 mt-3">

        <div class="col-12 my-4">
            <a href="{% url 'tasks:task_create' %}" class="btn btn-outline-dark">{% trans "Создать задачу" %}</a>
        </div>

        <div class="col-md-5 mb-3">
            <label class="form-label" for="id_name">{% trans "Имя задачи" %}</label>
            <input type="text" class="form-control" placeholder="{% trans "Имя задачи" %}" name="name" value="{{ request.GET.name }}">
        </div>
        <div class="col-md-5 mb-3">
            <label class="form-label" for="id_project">{% trans "Проект" %}</label>
            <select class="form-control" name="project" id="id_project">
                <option selected></option>
                {% for project in projects %}
                    <option value="{{ project.id }}" {% if request.GET.project == project.id|stringformat:"s" %}selected{% endif %}>{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-5 mb-3">
            <label class="form-label" for="id_priority">{% trans "Приоритет" %}</label>
            <select class="form-control" name="priority" id="id_priority">
                <option selected></option>
                {% for priority in priorities %}
                    <option value="{{ priority.id }}" {% if request.GET.priority == priority.id|stringformat:"s" %}selected{% endif %}>{{ priority.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-5 mb-3">
            <label class="form-label" for="id_status">{% trans "Статус" %}</label>
            <select class="form-control" name="status" id="id_status">
                <option selected></option>
                {% for status in statuses %}
                    <option value="{{ status.id }}" {% if request.GET.status == status.id|stringformat:"s" %}selected{% endif %}>{{ status.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-5 mb-3">
        </div>
        <div class="col-md-5 mb-3">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" name="is_closed" id="id_is_closed" {% if request.GET.is_closed %}checked{% endif %}>
                <label class="form-check-label" for="id_is_closed">{% trans "Только открытые задачи" %}</label>
            </div>
        </div>

        <div class="col-10 my-4">
            <div id="label-pills">
                {% for label in labels %}
                    <button type="button" class="btn btn-sm btn-outline-dark btn-pill rounded-pill my-1"
                            data-label-id="{{ label.id }}">
                        {{ label.name }}</button>
                {% endfor %}
            </div>
            <!-- Скрытое поле для хранения выбранных меток -->
            <input type="hidden" name="label" id="selected-labels" value="{{ request.GET.label }}">
        </div>
        <div class="col-12 mb-3">
            <button type="submit" class="btn btn-outline-dark">{% trans "Показать" %}</button>
        </div>
    </form>

  <table class="table table-hover">
    <thead class="bg-light">
      <tr>
        <th>{% trans "ID" %}</th>
        <th>{% trans "Имя" %}</th>
        <th>{% trans "Статус" %}</th>
        <th>{% trans "Приоритет" %}</th>
        <th>{% trans "Проект" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <td>{{ task.id }}</td>
          <td><a href="{% url 'tasks:task_detail' task.id %}">{{ task.name }}</a></td>
          <td>{{ task.status }}</td>
          <td>{{ task.priority }}</td>
          <td>{{ task.project }}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Действия">
              <a href="{% url 'tasks:task_update' task.id %}" class="btn btn-link">
                <i class="bi bi-pencil text-secondary"></i>
              </a>
              <a href="{% url 'tasks:task_delete' task.id %}" class="btn btn-link">
                <i class="bi bi-trash text-secondary"></i>
              </a>
            </div>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="7">{% trans "Нет задач." %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="mb-5"></div>
{% endblock %}